# dependabot configuration for hextra version update
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "06:00"
      timezone: UTC
    allow:
      # direct and indirect updates
      - dependency-type: "all"
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 1
